title: Sravya Thoomu
#logo: 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 10+ years of Experience.
  <br>
  <br>
  Education			       		
   M.S., Applied Mathematics and Mechanical Engineering,	Clemson University (Aug 2010)
theme: jekyll-theme-minimal
