title: Sravya Thoomu
#logo: 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Experienced data scientist with a proven track record of 10+ years in the field. Skilled in leveraging data-driven insights to drive business decisions and optimize processes. Possessing expertise in statistical analysis, machine learning, and predictive modeling, successfully developed, and implemented innovative solutions to complex business problems. Strong proficiency in programming languages such as Python and R, and proficiency in data manipulation and visualization tools like Alteryx, SQL, and Tableau.
theme: jekyll-theme-minimal
