title: Sravya Thoomu
logo: "/images/0052.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 10+ years of Experience.
  <br>
  <br>      		
  M.S., Applied Mathematics and Mechanical Engineering,	Clemson University (Aug 2010) 
theme: jekyll-theme-minimal
